# Setup
title: Dark Poole
url: https://osamahansari.github.io/ProjectTalos/
paginate: 1
baseurl: "/ProjectTalos"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Osamah Ansari
  url: https://osamahansari.github.io/
  email: oaansari@umich.edu

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /ProjectTalos/archive

  - title: About
    url: /ProjectTalos/about
